Misc Improvements
Strikeeaglechase/VTOLLiveViewerClient pull request #1
Opened 2022-07-24 19:40 UTC by AlexAndHisScripts

Changed welcome screen, began throttle display support, limited camera zoom-in.

2022-07-25 14:16 UTC, Strikeeaglechase requested changes

2022-07-25 14:16 UTC, Strikeeaglechase commented on src/viewer/app.ts
> +	isOfflineTest = false;
Make sure variables have been marked as public, private, or protected

2022-07-25 14:16 UTC, Strikeeaglechase commented on src/viewer/entities/playerVehicle.ts
> +		if (this.app.isOfflineTest && this.lastTestingCMSDispense + 6000 < Date.now()) {
Testing code like this should go into the offlineTestSetup, you can use `setInterval` to create a loop that calls the fireCm method at some rate.

2022-07-25 14:16 UTC, Strikeeaglechase commented on src/viewer/entityBase/entity.ts
> +	private engineOffsets: object | null;
Don't use `object` typing, its equivalent to `any`, this should be `Vector[]`

2022-07-25 14:16 UTC, Strikeeaglechase commented on src/viewer/meshLoader/meshLoader.ts
> +	engineOffsets: object | null;
Don't use `object`. Should be an optional type so we don't have to put an empty array on every config object. The type should probably be `engineOffsets?: Vector[]`

2022-07-25 14:16 UTC, Strikeeaglechase commented on src/viewer/meshLoader/meshLoader.ts
> +		if (!config || !config.scaleDamper) return null;
Does `scaleDamper` affect engine offsets?

2022-07-25 19:56 UTC, AlexAndHisScripts commented
poke

2022-07-26 03:12 UTC, Strikeeaglechase approved these changes
pog ty

2022-07-26 03:12 UTC, merged